spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/inflearn/h2/testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  redis:
    host: 192.168.24.220
    port: 6379
    password: Ehfdkdhkwnj12!
